apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prefect-server
  namespace: prefect
spec:
  releaseName: prefect
  serviceAccountName: data-engineering
  chart:
    spec:
      chart: prefect-server
      sourceRef:
        kind: HelmRepository
        name: prefecthq-server
        namespace: prefect
      version: "*"
  interval: 1h0m0s
  # https://github.com/PrefectHQ/server/blob/master/helm/prefect-server/values.yaml
  # Just values which would be the same in prod and dev
