apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prefect-server
  namespace: prefect2
spec:
  values:
    postgresql:
      enabled: true
      auth:
        # -- determines whether an admin user is created within postgres
        enablePostgresUser: false
        database: server
        # -- name for a custom user
        username: prefect
        ## This is the password for `username` and will be set within the secret `{fullnameOverride}-postgresql` at the key `password`.
        ## This argument is only relevant when using the Postgres database included in the chart.
        ## For an external postgres connection, you must create and use `existingSecret` instead.
        # -- password for the custom user. Ignored if `auth.existingSecret` with key `password` is provided
        password: prefect-rocks
        existingSecret: ""
      containerPorts:
        postgresql: 5432

      # externalHostname defines the address to contact an externally
      # managed postgres database instance at. This is not required if
      # `internalPostgres` is `true`
      externalHostname: ""

      # -- enable use of bitnami/postgresql subchart
      useSubChart: true
