apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prefect-worker
  namespace: prefect
spec:
  releaseName: prefect
  chart:
    spec:
      chart: prefect-worker
      sourceRef:
        kind: HelmRepository
        name: prefecthq
        namespace: prefect
      version: "*"
  interval: 1h0m0s
  values:
    namespaceOverride: "prefect"
    worker:
      apiConfig: server # can be cloud if using prefect-cloud paid version or server for self deployed prefect-server
      config:
        workPool: kubernetes-local-work-pool-1 # work pool which worker will serve
      serverApiConfig:
        apiUrl: http://prefect-server.prefect.svc.cluster.local:4200/api # container server address
