apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prefect-server
  namespace: prefect2
spec:
  releaseName: prefect-server
  # serviceAccountName: data-engineering
  chart:
    spec:
      chart: prefect-server
      sourceRef:
        kind: HelmRepository
        name: prefecthq
        namespace: prefect2
      version: "*"
  interval: 1h0m0s
  values:
    server:
      image:
        prefectTag: 2.14.10-python3.9
  # https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-server/values.yaml
  # Just values which would be the same in prod and dev
  